import type { Metadata } from "next";
import { Michroma, Montserrat, Rubik, Roboto, Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/layout/Header";
import Footer from "./components/layout/Footer";
// import NextTopLoader from 'nextjs-toploader';

// Font imports and config
const michroma = Michroma({
  weight: "400",
  subsets: ["latin"],
  // variable: "--font-michroma",
  display: "swap",
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // Adjust weights as needed
  display: "swap",
});

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // include multiple weights as needed
  // variable: "--font-montserrat",
  display: "swap",
});

const rubik = Rubik({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // include multiple weights as needed
  // variable: "--font-rubik",
  display: "swap",
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${rubik.className} ${inter.className} ${michroma.className} ${montserrat.className} ${roboto?.className} font-sans`}
      >
          <Header />
          <main className="min-h-screen"> {children}</main>
          <Footer />
      </body>
    </html>
  );
}
